### ISSUE TITLE
[Bug] Dragourd crashes game/server when attacking.

### ISSUE THREAD

**Issue by grundyboy34** [BlueDuckYT/Mystical-Pumpkins#1]
Forge version: 34.1.35
Mystical Pumpkins version: 0.1.3
Geckolib version: 2.1.2

When a dragourd attacks a player, the server crashes.

**Comment by LorenzoPapi** [comment]
Send crash report and latest.log

**Comment by grundyboy34** [comment]
https://pastebin.com/mVfuWjKy

**Comment by grundyboy34** [comment]
My guess is these anim calls need to be wrapped in a if (world.isRemote) block
https://github.com/BlueDuckYT/Mystical-Pumpkins/blob/dd6d8e3cff1ea4f8bb5b6a69cae6d4e4cc7068a9/src/main/java/blueduck/mysticalpumpkins/entity/DragourdEntity.java#L75-L76

**Comment by BlueDuckYT** [comment]
Fixed!  Thanks for letting us know
